version: '3.8'
services:
  mysqlsrv:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "contatosdb"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql-C:/var/lib/mysql
    networks:
      - minha-rede
  contacts-app:
    build: .
    environment:
      DbServer: "mysqlsrv"
      DbPort: "3306"
      DbUser: "root"
      Password: "admin"
      Database: "contatosdb"
    ports: 
      - "8080:80"
networks: 
  minha-rede:
    driver: bridge